import { PrismaClient, type Prisma } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  //Limpar dados anteriores
  await prisma.emprestimo.deleteMany()
  await prisma.livro.deleteMany()

  //Livros
  const livrosData: Prisma.LivroCreateManyInput[] = [
      {
        titulo: 'Clean Code',
        autor: 'Robert C. Martin',
        isbn: '9780132350884',
        editora: 'Prentice Hall',
        ano: 2008,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Design Patterns',
        autor: 'Gang of Four',
        isbn: '9780201633610',
        editora: 'Addison-Wesley',
        ano: 1994,
        quantidadeTotal: 3,
        quantidadeDisponivel: 1,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'The Pragmatic Programmer',
        autor: 'David Thomas, Andrew Hunt',
        isbn: '9780201616224',
        editora: 'Addison-Wesley',
        ano: 1999,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Introduction to Algorithms',
        autor: 'Thomas Cormen',
        isbn: '9780262033848',
        editora: 'MIT Press',
        ano: 2009,
        quantidadeTotal: 6,
        quantidadeDisponivel: 4,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Code Complete',
        autor: 'Steve McConnell',
        isbn: '9780735619678',
        editora: 'Microsoft Press',
        ano: 2004,
        quantidadeTotal: 3,
        quantidadeDisponivel: 3,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Refactoring',
        autor: 'Martin Fowler',
        isbn: '9780201485677',
        editora: 'Addison-Wesley',
        ano: 1999,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'The Mythical Man-Month',
        autor: 'Frederick Brooks',
        isbn: '9780201835959',
        editora: 'Addison-Wesley',
        ano: 1995,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Working Effectively with Legacy Code',
        autor: 'Michael Feathers',
        isbn: '9780131177055',
        editora: 'Prentice Hall',
        ano: 2004,
        quantidadeTotal: 3,
        quantidadeDisponivel: 1,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Cracking the Coding Interview',
        autor: 'Gayle Laakmann McDowell',
        isbn: '9780984782857',
        editora: 'CareerCup',
        ano: 2015,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'You Don\'t Know JS',
        autor: 'Kyle Simpson',
        isbn: '9781491924464',
        editora: 'O\'Reilly',
        ano: 2015,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Eloquent JavaScript',
        autor: 'Marijn Haverbeke',
        isbn: '9781593279509',
        editora: 'No Starch Press',
        ano: 2018,
        quantidadeTotal: 3,
        quantidadeDisponivel: 3,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'The Rust Book',
        autor: 'Steve Klabnik',
        isbn: '9781492046929',
        editora: 'O\'Reilly',
        ano: 2023,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Learning Python',
        autor: 'Mark Lutz',
        isbn: '9781449355739',
        editora: 'O\'Reilly',
        ano: 2013,
        quantidadeTotal: 6,
        quantidadeDisponivel: 4,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Dive Into Python',
        autor: 'Mark Pilgrim',
        isbn: '9781491936931',
        editora: 'O\'Reilly',
        ano: 2014,
        quantidadeTotal: 3,
        quantidadeDisponivel: 1,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'The C Programming Language',
        autor: 'Brian Kernighan',
        isbn: '9780131103627',
        editora: 'Prentice Hall',
        ano: 1988,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'JavaScript: The Definitive Guide',
        autor: 'David Flanagan',
        isbn: '9781491952023',
        editora: 'O\'Reilly',
        ano: 2020,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'High Performance JavaScript',
        autor: 'Nicholas Zakas',
        isbn: '9780596802806',
        editora: 'O\'Reilly',
        ano: 2010,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Web Performance in Action',
        autor: 'Jeremy Wagner',
        isbn: '9781617294631',
        editora: 'Manning',
        ano: 2016,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Microservices Patterns',
        autor: 'Chris Richardson',
        isbn: '9781617294549',
        editora: 'Manning',
        ano: 2018,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Domain-Driven Design',
        autor: 'Eric Evans',
        isbn: '9780321125675',
        editora: 'Addison-Wesley',
        ano: 2003,
        quantidadeTotal: 2,
        quantidadeDisponivel: 1,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'O Cortiço',
        autor: 'Aluísio Azevedo',
        isbn: '9788535908770',
        editora: 'Companhia das Letras',
        ano: 1890,
        quantidadeTotal: 6,
        quantidadeDisponivel: 4,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Dom Casmurro',
        autor: 'Machado de Assis',
        isbn: '9788535907438',
        editora: 'Companhia das Letras',
        ano: 1899,
        quantidadeTotal: 7,
        quantidadeDisponivel: 3,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Grande Sertão Veredas',
        autor: 'Guimarães Rosa',
        isbn: '9788535908771',
        editora: 'Nova Fronteira',
        ano: 1956,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Capitães da Areia',
        autor: 'Jorge Amado',
        isbn: '9788535922905',
        editora: 'Companhia das Letras',
        ano: 1937,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Gabriela, Cravo e Canela',
        autor: 'Jorge Amado',
        isbn: '9788535924305',
        editora: 'Companhia das Letras',
        ano: 1958,
        quantidadeTotal: 6,
        quantidadeDisponivel: 4,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'O Primo Basílio',
        autor: 'Eça de Queirós',
        isbn: '9788535908772',
        editora: 'L&PM',
        ano: 1878,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Os Maias',
        autor: 'Eça de Queirós',
        isbn: '9788535902373',
        editora: 'L&PM',
        ano: 1888,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Memórias Póstumas de Brás Cubas',
        autor: 'Machado de Assis',
        isbn: '9788535903539',
        editora: 'Companhia das Letras',
        ano: 1881,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Quincas Borba',
        autor: 'Machado de Assis',
        isbn: '9788535904529',
        editora: 'Companhia das Letras',
        ano: 1891,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'Vidas Secas',
        autor: 'Graciliano Ramos',
        isbn: '9788525407240',
        editora: 'Record',
        ano: 1938,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'São Bernardo',
        autor: 'Graciliano Ramos',
        isbn: '9788525408956',
        editora: 'Record',
        ano: 1934,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'O Corvo',
        autor: 'Edgar Allan Poe',
        isbn: '9788535902013',
        editora: 'Globo Livros',
        ano: 1845,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'O Alienista',
        autor: 'Machado de Assis',
        isbn: '9788535909043',
        editora: 'L&PM',
        ano: 1882,
        quantidadeTotal: 3,
        quantidadeDisponivel: 1,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Eugênia Grandet',
        autor: 'Honoré de Balzac',
        isbn: '9788535908773',
        editora: 'Editora 34',
        ano: 1833,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'A Dama das Camélias',
        autor: 'Alexandre Dumas',
        isbn: '9788535902014',
        editora: 'Globo Livros',
        ano: 1852,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'História do Brasil',
        autor: 'Boris Fausto',
        isbn: '9788535909044',
        editora: 'Edusp',
        ano: 1994,
        quantidadeTotal: 8,
        quantidadeDisponivel: 5,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'A Revolução Francesa',
        autor: 'Georges Lefebvre',
        isbn: '9788501083869',
        editora: 'UNESP',
        ano: 1989,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'O Mundo Moderno',
        autor: 'Eric Hobsbawm',
        isbn: '9788532524937',
        editora: 'Companhia das Letras',
        ano: 1995,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Império Romano',
        autor: 'Mary Beard',
        isbn: '9788532529640',
        editora: 'Companhia das Letras',
        ano: 2015,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'História da América Latina',
        autor: 'Luiz Felipe Alencastro',
        isbn: '9788525059302',
        editora: 'Rocco',
        ano: 2014,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Idade Média',
        autor: 'Jacques Le Goff',
        isbn: '9788532524936',
        editora: 'Civilização Brasileira',
        ano: 1995,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'A Revolução Industrial',
        autor: 'Eric Hobsbawm',
        isbn: '9788532524929',
        editora: 'Companhia das Letras',
        ano: 2009,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'História das Mulheres',
        autor: 'Michelle Perrot',
        isbn: '9788532524938',
        editora: 'Contexto',
        ano: 2007,
        quantidadeTotal: 3,
        quantidadeDisponivel: 1,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'O Renascimento',
        autor: 'Peter Burke',
        isbn: '9788525059326',
        editora: 'Rocco',
        ano: 2010,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'Breve História do Mundo',
        autor: 'Ernst Gombrich',
        isbn: '9788532524940',
        editora: 'Globo Livros',
        ano: 2001,
        quantidadeTotal: 5,
        quantidadeDisponivel: 4,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'História da Filosofia',
        autor: 'Frederick Copleston',
        isbn: '9788532524941',
        editora: 'Vozes',
        ano: 2000,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Absolutismo e Iluminismo',
        autor: 'Perry Anderson',
        isbn: '9788535902015',
        editora: 'Brasiliense',
        ano: 1985,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'História da Arte',
        autor: 'E.H. Gombrich',
        isbn: '9788532524942',
        editora: 'LTC',
        ano: 2012,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'A Criação do Mundo Atlântico',
        autor: 'Alison Games',
        isbn: '9788532524943',
        editora: 'Rocco',
        ano: 2011,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Guerras Napoleônicas',
        autor: 'Andrew Uffindell',
        isbn: '9788532524944',
        editora: 'Butterfly',
        ano: 2007,
        quantidadeTotal: 2,
        quantidadeDisponivel: 1,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'O Universo em uma Casca de Noz',
        autor: 'Stephen Hawking',
        isbn: '9788532524945',
        editora: 'Intrínseca',
        ano: 2001,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Cosmos',
        autor: 'Carl Sagan',
        isbn: '9788532521699',
        editora: 'Francisco Alves',
        ano: 1980,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Uma Breve História do Tempo',
        autor: 'Stephen Hawking',
        isbn: '9788532520241',
        editora: 'Rocco',
        ano: 1988,
        quantidadeTotal: 6,
        quantidadeDisponivel: 4,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'O Gene Egoísta',
        autor: 'Richard Dawkins',
        isbn: '9788532524946',
        editora: 'Rocco',
        ano: 1976,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'O Grande Projeto',
        autor: 'Stephen Hawking',
        isbn: '9788532529480',
        editora: 'Rocco',
        ano: 2010,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'Sapiens',
        autor: 'Yuval Harari',
        isbn: '9788532524947',
        editora: 'L&PM',
        ano: 2011,
        quantidadeTotal: 7,
        quantidadeDisponivel: 4,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Homo Deus',
        autor: 'Yuval Harari',
        isbn: '9788532530166',
        editora: 'L&PM',
        ano: 2015,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'A Origem das Espécies',
        autor: 'Charles Darwin',
        isbn: '9788532524948',
        editora: 'Itatiaia',
        ano: 1859,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Radiante',
        autor: 'Susan David',
        isbn: '9788532529481',
        editora: 'Rocco',
        ano: 2016,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'O Caminho da Criatividade',
        autor: 'Mihaly Csikszentmihalyi',
        isbn: '9788532524949',
        editora: 'Rocco',
        ano: 1996,
        quantidadeTotal: 2,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },

      {
        titulo: 'Harry Potter e a Pedra Filosofal',
        autor: 'J.K. Rowling',
        isbn: '9788532530787',
        editora: 'Rocco',
        ano: 2000,
        quantidadeTotal: 10,
        quantidadeDisponivel: 6,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'Harry Potter e a Câmara Secreta',
        autor: 'J.K. Rowling',
        isbn: '9788532530794',
        editora: 'Rocco',
        ano: 2000,
        quantidadeTotal: 8,
        quantidadeDisponivel: 4,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'Percy Jackson e o Ladrão de Raios',
        autor: 'Rick Riordan',
        isbn: '9788532524683',
        editora: 'Intrínseca',
        ano: 2005,
        quantidadeTotal: 7,
        quantidadeDisponivel: 4,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'O Pequeno Príncipe',
        autor: 'Antoine de Saint-Exupéry',
        isbn: '9788532524939',
        editora: 'Rocco',
        ano: 1943,
        quantidadeTotal: 9,
        quantidadeDisponivel: 6,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'Alice no País das Maravilhas',
        autor: 'Lewis Carroll',
        isbn: '9788532521700',
        editora: 'Rocco',
        ano: 1865,
        quantidadeTotal: 6,
        quantidadeDisponivel: 4,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Matilda',
        autor: 'Roald Dahl',
        isbn: '9788532530788',
        editora: 'Rocco',
        ano: 1988,
        quantidadeTotal: 5,
        quantidadeDisponivel: 3,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'O Fantástico Sr. Raposo',
        autor: 'Roald Dahl',
        isbn: '9788532530789',
        editora: 'Rocco',
        ano: 1970,
        quantidadeTotal: 4,
        quantidadeDisponivel: 2,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'O Hobbit',
        autor: 'J.R.R. Tolkien',
        isbn: '9788533613370',
        editora: 'Martins Fontes',
        ano: 1937,
        quantidadeTotal: 6,
        quantidadeDisponivel: 3,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'A Menina que Roubava Livros',
        autor: 'Markus Zusak',
        isbn: '9788532524950',
        editora: 'Intrínseca',
        ano: 2005,
        quantidadeTotal: 5,
        quantidadeDisponivel: 2,
        categoria: 'CIENCIAS',
      },
      {
        titulo: 'Diário de um Banana',
        autor: 'Jeff Kinney',
        isbn: '9788532523273',
        editora: 'Rocco',
        ano: 2007,
        quantidadeTotal: 8,
        quantidadeDisponivel: 5,
        categoria: 'HISTORIA',
      },
      {
        titulo: 'Tá Chovendo Hambúrguer',
        autor: 'Judi Barrett',
        isbn: '9788532524951',
        editora: 'Rocco',
        ano: 1978,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'ROMANCE',
      },
      {
        titulo: 'A Revolução dos Bichos',
        autor: 'George Orwell',
        isbn: '9788532524952',
        editora: 'Rocco',
        ano: 1945,
        quantidadeTotal: 5,
        quantidadeDisponivel: 2,
        categoria: 'TECNOLOGIA',
      },
      {
        titulo: 'As Aventuras de Tom Sawyer',
        autor: 'Mark Twain',
        isbn: '9788532524953',
        editora: 'Martin Claret',
        ano: 1876,
        quantidadeTotal: 3,
        quantidadeDisponivel: 2,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'O Livreiro de Cabul',
        autor: 'Áshin Ali',
        isbn: '9788532524954',
        editora: 'Rocco',
        ano: 2002,
        quantidadeTotal: 4,
        quantidadeDisponivel: 3,
        categoria: 'INFANTIL',
      },
      {
        titulo: 'Winnie-the-Pooh',
        autor: 'A.A. Milne',
        isbn: '9788532524955',
        editora: 'Rocco',
        ano: 1926,
        quantidadeTotal: 5,
        quantidadeDisponivel: 4,
        categoria: 'INFANTIL',
      },
  ]

  // Insere os livros começando com o estoque cheio (disponível = total);
  // a quantidade disponível é recalculada no final com base nos empréstimos ativos.
  await prisma.livro.createMany({
    data: livrosData.map((livro) => ({
      ...livro,
      quantidadeDisponivel: livro.quantidadeTotal,
    })),
  })

  //Guardar os livros para buscar a Id depois (ordenado para mapeamento determinístico)
  const livrosDoDb = await prisma.livro.findMany({ orderBy: { isbn: 'asc' } })

  //Empréstimos
  const emprestimosData: Prisma.EmprestimoCreateManyInput[] = [
      {
        livroId: livrosDoDb[0].id,
        nomeCliente: 'João Silva',
        emailCliente: 'joao@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[1].id,
        nomeCliente: 'Maria Santos',
        emailCliente: 'maria.santos@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
        status: "DEVOLVIDO",
      },
      {
        livroId: livrosDoDb[2].id,
        nomeCliente: 'Pedro Costa',
        emailCliente: 'pedro.costa@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[3].id,
        nomeCliente: 'Ana Oliveira',
        emailCliente: 'ana.oliveira@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[7].id,
        nomeCliente: 'Carlos Ferreira',
        emailCliente: 'carlos.ferreira@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
        status: "DEVOLVIDO",
      },
      {
        livroId: livrosDoDb[5].id,
        nomeCliente: 'Laura Mendes',
        emailCliente: 'laura.mendes@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[6].id,
        nomeCliente: 'Roberto Silva',
        emailCliente: 'roberto.silva@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[7].id,
        nomeCliente: 'Juliana Costa',
        emailCliente: 'juliana.costa@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[8].id,
        nomeCliente: 'Bruno Teixeira',
        emailCliente: 'bruno.teixeira@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
        status:"DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[9].id,
        nomeCliente: 'Fernanda Lima',
        emailCliente: 'fernanda.lima@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[10].id,
        nomeCliente: 'Ricardo Alves',
        emailCliente: 'ricardo.alves@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[11].id,
        nomeCliente: 'Patrícia Gomes',
        emailCliente: 'patricia.gomes@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[12].id,
        nomeCliente: 'Marcelo Souza',
        emailCliente: 'marcelo.souza@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[13].id,
        nomeCliente: 'Camila Barbosa',
        emailCliente: 'camila.barbosa@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[14].id,
        nomeCliente: 'Diego Rocha',
        emailCliente: 'diego.rocha@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[15].id,
        nomeCliente: 'Thaysa Martins',
        emailCliente: 'thaysa.martins@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[16].id,
        nomeCliente: 'Felipe Nascimento',
        emailCliente: 'felipe.nascimento@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[17].id,
        nomeCliente: 'Isabela Moura',
        emailCliente: 'isabela.moura@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[18].id,
        nomeCliente: 'Gustavo Pereira',
        emailCliente: 'gustavo.pereira@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
      },
      {
        livroId: livrosDoDb[19].id,
        nomeCliente: 'Amanda Carvalho',
        emailCliente: 'amanda.carvalho@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-06-20'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[20].id,
        nomeCliente: 'João Silva',
        emailCliente: 'joao@email.com',
        dataLocacao: new Date('2026-04-01'),
        dataPrevistaDevolucao: new Date('2026-05-01'),
      },
      {
        livroId: livrosDoDb[21].id,
        nomeCliente: 'Maria Santos',
        emailCliente: 'maria.santos@email.com',
        dataLocacao: new Date('2026-04-05'),
        dataPrevistaDevolucao: new Date('2026-05-05'),
      },
      {
        livroId: livrosDoDb[22].id,
        nomeCliente: 'Pedro Costa',
        emailCliente: 'pedro.costa@email.com',
        dataLocacao: new Date('2026-04-10'),
        dataPrevistaDevolucao: new Date('2026-05-10'),
      },
      {
        livroId: livrosDoDb[23].id,
        nomeCliente: 'Ana Oliveira',
        emailCliente: 'ana.oliveira@email.com',
        dataLocacao: new Date('2026-04-15'),
        dataPrevistaDevolucao: new Date('2026-05-15'),
      },
      {
        livroId: livrosDoDb[24].id,
        nomeCliente: 'Carlos Ferreira',
        emailCliente: 'carlos.ferreira@email.com',
        dataLocacao: new Date('2026-03-20'),
        dataPrevistaDevolucao: new Date('2026-04-20'),
        status: 'DEVOLVIDO'
      },
      {
        livroId: livrosDoDb[25].id,
        nomeCliente: 'Laura Mendes',
        emailCliente: 'laura.mendes@email.com',
        dataLocacao: new Date('2026-03-25'),
        dataPrevistaDevolucao: new Date('2026-04-25'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[26].id,
        nomeCliente: 'Roberto Silva',
        emailCliente: 'roberto.silva@email.com',
        dataLocacao: new Date('2026-04-02'),
        dataPrevistaDevolucao: new Date('2026-05-02'),
      },
      {
        livroId: livrosDoDb[27].id,
        nomeCliente: 'Juliana Costa',
        emailCliente: 'juliana.costa@email.com',
        dataLocacao: new Date('2026-04-08'),
        dataPrevistaDevolucao: new Date('2026-05-08'),
      },
      {
        livroId: livrosDoDb[28].id,
        nomeCliente: 'Bruno Teixeira',
        emailCliente: 'bruno.teixeira@email.com',
        dataLocacao: new Date('2026-04-12'),
        dataPrevistaDevolucao: new Date('2026-05-12'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[29].id,
        nomeCliente: 'Fernanda Lima',
        emailCliente: 'fernanda.lima@email.com',
        dataLocacao: new Date('2026-03-30'),
        dataPrevistaDevolucao: new Date('2026-04-30'),
      },
      {
        livroId: livrosDoDb[30].id,
        nomeCliente: 'Ricardo Alves',
        emailCliente: 'ricardo.alves@email.com',
        dataLocacao: new Date('2026-04-03'),
        dataPrevistaDevolucao: new Date('2026-05-03'),
      },
      {
        livroId: livrosDoDb[31].id,
        nomeCliente: 'Patrícia Gomes',
        emailCliente: 'patricia.gomes@email.com',
        dataLocacao: new Date('2026-04-07'),
        dataPrevistaDevolucao: new Date('2026-05-07'),
      },
      {
        livroId: livrosDoDb[32].id,
        nomeCliente: 'Marcelo Souza',
        emailCliente: 'marcelo.souza@email.com',
        dataLocacao: new Date('2026-04-11'),
        dataPrevistaDevolucao: new Date('2026-05-11'),
      },
      {
        livroId: livrosDoDb[33].id,
        nomeCliente: 'Camila Barbosa',
        emailCliente: 'camila.barbosa@email.com',
        dataLocacao: new Date('2026-04-14'),
        dataPrevistaDevolucao: new Date('2026-05-14'),
      },
      {
        livroId: livrosDoDb[34].id,
        nomeCliente: 'Diego Rocha',
        emailCliente: 'diego.rocha@email.com',
        dataLocacao: new Date('2026-03-22'),
        dataPrevistaDevolucao: new Date('2026-04-22'),
      },
      {
        livroId: livrosDoDb[35].id,
        nomeCliente: 'Thaysa Martins',
        emailCliente: 'thaysa.martins@email.com',
        dataLocacao: new Date('2026-04-04'),
        dataPrevistaDevolucao: new Date('2026-05-04'),
      },
      {
        livroId: livrosDoDb[36].id,
        nomeCliente: 'Felipe Nascimento',
        emailCliente: 'felipe.nascimento@email.com',
        dataLocacao: new Date('2026-04-09'),
        dataPrevistaDevolucao: new Date('2026-05-09'),
      },
      {
        livroId: livrosDoDb[37].id,
        nomeCliente: 'Isabela Moura',
        emailCliente: 'isabela.moura@email.com',
        dataLocacao: new Date('2026-04-13'),
        dataPrevistaDevolucao: new Date('2026-05-13'),
      },
      {
        livroId: livrosDoDb[38].id,
        nomeCliente: 'Gustavo Pereira',
        emailCliente: 'gustavo.pereira@email.com',
        dataLocacao: new Date('2026-03-28'),
        dataPrevistaDevolucao: new Date('2026-04-28'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[39].id,
        nomeCliente: 'Amanda Carvalho',
        emailCliente: 'amanda.carvalho@email.com',
        dataLocacao: new Date('2026-04-06'),
        dataPrevistaDevolucao: new Date('2026-05-06'),
      },
      {
        livroId: livrosDoDb[40].id,
        nomeCliente: 'João Silva',
        emailCliente: 'joao@email.com',
        dataLocacao: new Date('2026-03-01'),
        dataPrevistaDevolucao: new Date('2026-04-01'),
      },
      {
        livroId: livrosDoDb[41].id,
        nomeCliente: 'Maria Santos',
        emailCliente: 'maria.santos@email.com',
        dataLocacao: new Date('2026-02-15'),
        dataPrevistaDevolucao: new Date('2026-03-15'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[0].id,
        nomeCliente: 'Pedro Costa',
        emailCliente: 'pedro.costa@email.com',
        dataLocacao: new Date('2026-05-10'),
        dataPrevistaDevolucao: new Date('2026-05-20'),
      },
      {
        livroId: livrosDoDb[1].id,
        nomeCliente: 'Ana Oliveira',
        emailCliente: 'ana.oliveira@email.com',
        dataLocacao: new Date('2026-02-20'),
        dataPrevistaDevolucao: new Date('2026-03-20'),
      },
      {
        livroId: livrosDoDb[2].id,
        nomeCliente: 'Carlos Ferreira',
        emailCliente: 'carlos.ferreira@email.com',
        dataLocacao: new Date('2026-01-30'),
        dataPrevistaDevolucao: new Date('2026-02-28'),
      },
      {
        livroId: livrosDoDb[45].id,
        nomeCliente: 'Laura Mendes',
        emailCliente: 'laura.mendes@email.com',
        dataLocacao: new Date('2026-03-10'),
        dataPrevistaDevolucao: new Date('2026-04-10'),
      },
      {
        livroId: livrosDoDb[46].id,
        nomeCliente: 'Roberto Silva',
        emailCliente: 'roberto.silva@email.com',
        dataLocacao: new Date('2026-02-01'),
        dataPrevistaDevolucao: new Date('2026-03-01'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[47].id,
        nomeCliente: 'Juliana Costa',
        emailCliente: 'juliana.costa@email.com',
        dataLocacao: new Date('2026-03-05'),
        dataPrevistaDevolucao: new Date('2026-04-05'),
      },
      {
        livroId: livrosDoDb[48].id,
        nomeCliente: 'Bruno Teixeira',
        emailCliente: 'bruno.teixeira@email.com',
        dataLocacao: new Date('2026-04-01'),
        dataPrevistaDevolucao: new Date('2026-05-01'),
      },
      {
        livroId: livrosDoDb[49].id,
        nomeCliente: 'Fernanda Lima',
        emailCliente: 'fernanda.lima@email.com',
        dataLocacao: new Date('2026-02-10'),
        dataPrevistaDevolucao: new Date('2026-03-10'),
      },
      {
        livroId: livrosDoDb[50].id,
        nomeCliente: 'Ricardo Alves',
        emailCliente: 'ricardo.alves@email.com',
        dataLocacao: new Date('2026-01-20'),
        dataPrevistaDevolucao: new Date('2026-02-20'),
      },
      {
        livroId: livrosDoDb[51].id,
        nomeCliente: 'Patrícia Gomes',
        emailCliente: 'patricia.gomes@email.com',
        dataLocacao: new Date('2026-03-15'),
        dataPrevistaDevolucao: new Date('2026-04-15'),
      },
      {
        livroId: livrosDoDb[5].id,
        nomeCliente: 'Marcelo Souza',
        emailCliente: 'marcelo.souza@email.com',
        dataLocacao: new Date('2026-02-25'),
        dataPrevistaDevolucao: new Date('2026-03-25'),
        status: "DEVOLVIDO"
      },
      {
        livroId: livrosDoDb[53].id,
        nomeCliente: 'Camila Barbosa',
        emailCliente: 'camila.barbosa@email.com',
        dataLocacao: new Date('2026-04-10'),
        dataPrevistaDevolucao: new Date('2026-05-10'),
      },
      {
        livroId: livrosDoDb[6].id,
        nomeCliente: 'Diego Rocha',
        emailCliente: 'diego.rocha@email.com',
        dataLocacao: new Date('2026-03-20'),
        dataPrevistaDevolucao: new Date('2026-04-20'),
      },
      {
        livroId: livrosDoDb[55].id,
        nomeCliente: 'Paulo Braz',
        emailCliente: 'paulo.braz@email.com',
        dataLocacao: new Date('2026-03-20'),
        dataPrevistaDevolucao: new Date('2026-04-20'),
      },
      {
        livroId: livrosDoDb[3].id,
        nomeCliente: 'Diego Xavier',
        emailCliente: 'diego.xavier@email.com',
        dataLocacao: new Date('2026-05-20'),
        dataPrevistaDevolucao: new Date('2026-07-20'),
      },

  ]

  await prisma.emprestimo.createMany({
    data: emprestimosData,
  })

  // Recalcula a quantidade disponível: cada empréstimo ativo (não devolvido)
  // ocupa uma unidade do estoque do livro, exatamente como na criação real de um empréstimo.
  const ativosPorLivro = new Map<string, number>()
  for (const emprestimo of emprestimosData) {
    if (emprestimo.status === 'DEVOLVIDO') continue
    ativosPorLivro.set(
      emprestimo.livroId,
      (ativosPorLivro.get(emprestimo.livroId) ?? 0) + 1,
    )
  }

  for (const [livroId, ativos] of ativosPorLivro) {
    const livro = livrosDoDb.find((l) => l.id === livroId)!
    await prisma.livro.update({
      where: { id: livroId },
      data: { quantidadeDisponivel: Math.max(0, livro.quantidadeTotal - ativos) },
    })
  }

}

main()
  .catch((e) => {
    console.error('❌ Erro ao fazer seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })